class Settings(object):
    FRICTION = .05
    SCREEN_WIDTH=800
    SCREEN_HEIGHT=600

    TILE_WIDTH = 32
    TILE_HEIGHT = 32

    FIELD_X_OFFSET = 32
    YARDS_PER_TILE = 2
    FIELD_WIDTH_X = 640
    FIELD_WIDTH_TILES = FIELD_WIDTH_X // TILE_WIDTH
    FIELD_HEIGHT_TILES = 120 // YARDS_PER_TILE
    FIELD_HEIGHT_Y = FIELD_HEIGHT_TILES * TILE_HEIGHT
    
    LEFT_HASH_TILE_X = 6
    RIGHT_HASH_TILE_X = 15
